### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by johnwmillr** [tsandefer/dsi_capstone_3#2]
Hi @tsandefer, this is a really cool project! I'm glad you were able to put my [LyricsGenius](https://github.com/johnwmillr/LyricsGenius) package to good use. Do you mind if I add a link to your project on the Examples section of the LyricsGenius documentation?

Thanks!
John

**Comment by tsandefer** [comment]
Hi John!

Wow, it's great to hear from you, I'm excited to hear you liked the
project! I loved yours as well. Please feel free to add that link, I'm
honored! I certainly wouldn't have been able to do what I did without
LyricsGenius.

Best,
Taite

**Comment by johnwmillr** [comment]
Great, I've updated the readme!

John
